### ISSUE TITLE
report error

### ISSUE THREAD

**Issue by floydawong** [cpeccei/RenderTree#1]
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "C:\Users\wangjiayi\AppData\Roaming\Sublime Text 3\Installed Packages\Render Tree.sublime-package\render_tree.py", line 35, in run
UnboundLocalError: local variable 'child' referenced before assignment

**Comment by floydawong** [comment]
Sublime Text 3 Version 3.2.2 Build 3211
Windows 7

**Comment by andre-laurie** [comment]
Reading the code, this error happens when no tree structure, say no child under parent, is found in current selection.
Error occurs if you happen to select only one line... or more likely, if you forgot to convert those tabs into 4 spaces!

For example,
`MyOnlySelectedFlatNode
`
Or, trickier example
```
MyRoot
    MyChildPrependedWithTabInsteadOf4Spaces
```
